resources:
- daemon.yaml

configMapGenerator:
- literals:
  - logLevel=info
  - releaseVersion=1.1.0
  - serviceAccountName=nic-configuration-operator-controller-manager
  - configDaemonImage=harbor.mellanox.com/cloud-orchestration-dev/nic-configuration-operator-daemon:latest
  - clusterType=openshift
  name: config
  options:
    disableNameSuffixHash: true
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
