apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: nic-configuration-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: NicConfigurationTemplate is the Schema for the nicconfigurationtemplates
        API
      displayName: Nic Configuration Template
      kind: NicConfigurationTemplate
      name: nicconfigurationtemplates.configuration.net.nvidia.com
      version: v1alpha1
    - description: NicDevice is the Schema for the nicdevices API
      displayName: Nic Device
      kind: NicDevice
      name: nicdevices.configuration.net.nvidia.com
      version: v1alpha1
  description: .
  displayName: nic-config-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - operator
  links:
  - name: Nic Configuration Operator
    url: https://nic-configuration-operator.domain
  maturity: alpha
  provider:
    name: Nvidia NIC Config Operator
  version: 0.0.0
